### ISSUE TITLE
想咨询下

### ISSUE THREAD

**Issue by dirlang** [mequanwei/CQUPTThesis#1]
先感谢开发者上传，想问下您当年是按这个模板写的吗，最后提交的时候更改的多吗？这个模板和学校给的格式是完全吻合的不，，如果是的话，就按您给的写了

**Comment by mequanwei** [comment]
可以直接使用。注意模板没有封面，最后提交时需要从学校的word导出PDF，然后自己拼接。

**Comment by dirlang** [comment]
我就说好像是没封面，，我还去CLS文件里面把注释掉的封面代码改了一下，也发现格式好像不太对。如果其他的没问题就ok！感谢感谢
